ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"
dual_boot:
  primary:
    name: Linux
    mount_point: /boot/EFI
    bootloader:
      entry_dir: /boot/loader/entries
  secondary:
    name: Windows
    mount_point: /mnt/windowsEFI
    esp: /dev/nvme0n1p1
    fstype: vfat
    sub_path: EFI/Microsoft
    bootloader:
      file: /boot/EFI/Microsoft/Boot/bootmgfw.efi
packages:
  - name: blueman
  - name: jq
  - name: networkmanager
  - name: networkmanager-dmenu
  - name: pacman-contrib
  - name: unzip
  - name: nvidia-open
  - name: nvidia-utils
  # - name: lib32-nvidia-utils
  - name: nvidia-settings
  - name: openssh

  - name: libnewt
  - name: hyprland
  - name: hyprcursor
  - name: hypridle
  - name: hyprlock
  - name: hyprpaper
  - name: imagemagick
  - name: uwsm
  - name: gnome-themes-extra

  - name: rust
  - name: discord
  - name: fastfetch
  - name: firefox
  - name: git
  - name: imv
  - name: kitty
  - name: less
  - name: nodejs
  - name: neovim
  - name: npm
  - name: pavucontrol
    # - name: plymouth
  - name: ripgrep
  - name: rofi
  - name: rsync
  - name: spotify-launcher
  - name: starship
  - name: tree
  - name: waybar
  - name: wl-clipboard
services:
  - name: NetworkManager.service
    scope: system
  - name: bluetooth.service
    scope: system
  - name: systemd-timesyncd.service
    scope: system
  - name: fstrim.timer
    scope: system
  - name: paccache.timer
    scope: system
  - name: sshd
    scope: system

  # This should be anabled on default
  - name: getty@tty1.service
    scope: system
  # Rescue tty session
  - name: getty@tty2.service
    scope: system
  - name: hypridle.service
  - name: hyprpaper.service

  - name: pipewire.service
  - name: pipewire-pulse.service
  - name: wireplumber.service
ssh:
  dir: "{{ ansible_facts.user_dir }}/.ssh"
  generate_keys:
    - filename: id_ed25519
      regenerate: partial_idempotence
      type: ed25519
devtools:
  python:
    pipx: true
    packages:
      - name: ansible
        install_deps: true
      - name: uv
  zig:
    zvm: true
tools:
  pipx_packages:
    - name: ansible
      install_deps: true
    - name: uv
  zig: true
  swww: true
dotfiles:
  config_dir: "{{ ansible_facts.user_dir }}/.config"
theming:
  gtk:
    url: https://github.com/vinceliuice/Graphite-gtk-theme/archive/refs/tags/2025-07-06.tar.gz
    dir: "{{ ansible_facts.user_dir }}/.local/share/themes"
  wallpapers:
    - dest: "{{ ansible_facts.user_dir }}/.config/hypr/wallpapers/catppuccin-mocha.png"
      url: https://w.wallhaven.cc/full/ex/wallhaven-exj2yl.png
    - dest: "{{ ansible_facts.user_dir }}/.config/hypr/wallpapers/everforest.jpg"
      url: https://w.wallhaven.cc/full/6q/wallhaven-6qj596.jpg
  font:
    name: JetBrainsMono Nerd Font Mono
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip
    dir: "{{ ansible_facts.user_dir }}/.local/share/fonts"
  cursor:
    name: catppuccin-mocha-blue-cursors
    url:  https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dir: "{{ ansible_facts.user_dir }}/.local/share/icons"

