ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"
base:
  dual_boot:
    primary:
      name: Linux
      mount_point: /boot/EFI
      bootloader:
        entry_dir: /boot/loader/entries
    secondary:
      name: Windows
      mount_point: /mnt/windowsEFI
      esp: /dev/nvme0n1p1
      fstype: vfat
      sub_path: EFI/Microsoft
      bootloader:
        file: /boot/EFI/Microsoft/Boot/bootmgfw.efi
  packages:
    - name: blueman
    - name: jq
    - name: networkmanager
    - name: networkmanager-dmenu
    - name: pacman-contrib
    - name: unzip
    - name: nvidia-open
    - name: nvidia-utils
    # - name: lib32-nvidia-utils
    - name: nvidia-settings
    - name: openssh
  services:
    - name: NetworkManager.service
      scope: system
    - name: bluetooth.service
      scope: system
    - name: systemd-timesyncd.service
      scope: system
    - name: fstrim.timer
      scope: system
    - name: paccache.timer
      scope: system
    - name: sshd
      scope: system
  ssh:
    dir: "{{ ansible_facts.user_dir }}/.ssh"
    generate_keys:
      - filename: id_ed25519
        regenerate: partial_idempotence
        type: ed25519
hyprland:
  packages:
    - name: libnewt
    - name: hyprland
    - name: hyprcursor
    - name: hypridle
    - name: hyprlock
    - name: hyprpaper
    - name: uwsm
  services:
    # This should be anabled on default
    - name: getty@tty1.service
      scope: system
    # Rescue tty session
    - name: getty@tty2.service
      scope: system
    - name: hypridle.service
    - name: hyprpaper.service
apps:
  packages:
    - name: discord
    - name: fastfetch
    - name: firefox
    - name: git
    - name: imv
    - name: kitty
    - name: less
    - name: neovim
      # - name: plymouth
    - name: ripgrep
    - name: rofi
    - name: rsync
    - name: spotify-launcher
    - name: starship
    - name: tree
    - name: waybar
    - name: wl-clipboard
    - name: wofi
    # - name: yay
  aur: []
  services:
    - name: pipewire.service
    - name: pipewire-pulse.service
    - name: wireplumber.service
    - name: xdg-desktop-portal.service
    - name: xdg-desktop-portal-hyprland.service
    - name: polkit-kde-agent.service
    - name: mako.service
devtools:
  python:
    packages:
      - name: python
      - name: python-pipx
    pipx_packages:
      - name: ansible
        install_deps: true
      - name: uv
  zig:
    zvm: true
aur:
  user: aur_builder
  helper: yay
  yay:
    packages:
      - name: base-devel
      - name: git
dotfiles:
  config_dir: "{{ ansible_facts.user_dir }}/.config"
theming:
  font:
    name: JetBrainsMono Nerd Font Mono
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip
    dir: "{{ ansible_facts.user_dir }}/.local/share/fonts"
  cursor:
    name: catppuccin-mocha-blue-cursors
    url:  https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dir: "{{ ansible_facts.user_dir }}/.local/share/icons"
