- name: Execute roles
  hosts: localhost
  collections:
    - arch.config
  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - base
        - bash
        - hyprland
        - theming
        - apps
        - devtools
      loop_control:
        loop_var: role

