- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ base.ssh.dir }}"
    state: directory
    mode: "0700"

- name: Generate ssh keys
  community.crypto.openssh_keypair:
    path: "{{ base.ssh.dir }}/{{ key.filename }}"
    passphrase: "{{ key.passphrase | default(omit) }}"
    type: "{{ key.type }}"
    state: "{{ key.state | default(omit) }}"
    regenerate: "{{ key.regenerate | default(omit) }}"
  loop: "{{ base.ssh.generate_keys }}"
  loop_control:
    loop_var: key

- name: Deploy ssh keys
  ansible.posix.authorized_key:
    user: "{{ ansible_facts.user_id }}"
    state: present
    key: "{{ lookup('file', base.ssh.dir + '/' + key.filename + '.pub') }}"
  loop: "{{ base.ssh.generate_keys }}"
  loop_control:
    loop_var: key
